### ISSUE TITLE
BIG REFACTOR: utilize goroutines and channels

### ISSUE THREAD

**Issue by saltkid** [saltkid/gorn#17]

**Comment by saltkid** [comment]
Make funcs smaller and create unit tests first before refactoring

**Comment by am-cid** [comment]
Only concurrent process I'm thinking of doing right now is the renaming part where there are no returned values (presence of errors will skip renaming the file/files under dir), and can be safely converted to concurrent. This is because the slices of paths, commands, flags, and other values to be used in renaming are all validated beforehand in synchronous processes (`TokenizeArgs`, `ParseArgs`, and `FetchEntries`)

**Comment by saltkid** [comment]
Only concurrent process I'm thinking of doing right now is the renaming part where there are no returned values (presence of errors will skip renaming the file/files under dir), and can be safely converted to concurrent. This is because the slices of paths, commands, flags, and other values to be used in renaming are all validated beforehand in synchronous processes (`TokenizeArgs`, `ParseArgs`, and `FetchEntries`)

**Comment by saltkid** [comment]
interesting that some processes (`info.Rename()`) are faster not using goroutines. might be because of the overhead of creating one

**Comment by saltkid** [comment]
i'm going to use async per type, sync entry renaming

sync per type, sync entry renaming
- ~190ms

async per type, sync entry renaming
- ~68ms

sync per type, async entry renaming
- ~75ms

async per type, asyng entry renaming
- ~80ms

**sync per type** means renaming all `series multiple seasons no movies` will wait for all `named seasons` to be done before starting.

**async per type** means each series/movie type is in its own goroutine. Renaming all `series multiple seasons no movies` will **NOT** wait for all `named seasons` to be done before starting.

**sync entry renaming** means renaming `bakemonogatari episode 10` will wait for `bakemonogatari episode 9` to be done before starting. each entry is still in their own goroutine and not blocking each other **BUT** the episodes are all in one goroutine which will wait for the previous one to finish before starting

**async entry renaming** means renaming `bakemonogatari episode 10` will **NOT** wait for `bakemonogatari episode 9` to be done before starting. each episode is in their own goroutine
